# -*- coding: utf-8 -*-
"""Gliner v4 - streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11a5QXVUEG5O56IHtVFpQVrAliIJdk2Ns
"""

!pip install streamlit

!pip install gliner

"""############text used for examples in the past James Short and John Harrison: personal genius and public knowledge
Jim Bennett
Abstract
https://dx.doi.org/10.15180/140209/001
The instrument maker James Short, whose output was exclusively reflecting telescopes, was a sustained and consistent supporter of the clock and watch maker John Harrison. Short’s specialism placed his work in a tradition that derived from Newton’s Opticks, where the natural philosopher or mathematician might engage in the mechanical process of making mirrors, and a number of prominent astronomers followed this example in the eighteenth century. However, it proved difficult, if not impossible, to capture and communicate in words the manual skills they had acquired. Harrison’s biography has similarities with Short’s but, although he was well received and encouraged in London, unlike Short his mechanical practice did not place him at the centre of the astronomers’ agenda. Harrison became a small part of the growing public interest in experimental demonstration and display, and his timekeepers became objects of exhibition and resort. Lacking formal training, he himself came to be seen as a naive or intuitive mechanic, possessed of an individual and natural ‘genius’ for his work – an idea likely to be favoured by Short and his circle, and appropriate to Short’s intellectual roots in Edinburgh. The problem of capturing and communicating Harrison’s skill became acute once he was a serious candidate for a longitude award and was the burden of the specially appointed ‘Commissioners for the Discovery of Mr Harrison’s Watch’, whose members included Short. Now the problem was one of transforming individual genius into a generally useful practice. It was a question that touched on the reputation of Short in the area of his own genius and it was familiar also to the astronomers, men who had engaged with making mirrors, had struggled to systematise and record their methods, and who now, as Commissioners, had to judge whether and how Harrison’s very individual achievements might be shared.
Keywords
genius, marine timekeepers, optics, telescopes
Introduction
https://dx.doi.org/10.15180/140209/002
Marking the 300th anniversary of the 1714 Longitude Act has been an occasion for enriching our understanding of the eighteenth-century context for the longitude problem and its solutions. Recent work has achieved a more balanced and nuanced approach to the episode than one animated by the opposition of good and bad, right and wrong, virtue and trickery. The exhibition at the National Maritime Museum offers a richer, historically more plausible and altogether more interesting story, supported in the same vein by the accompanying book (Dunn and Higgitt, 2014), while the programme of the related conference expanded the context for longitude work out to the broadest social, political and economic issues of the day[1].
This paper seeks to contribute to this trend by showing that some of the big questions raised by Harrison’s work, concerning universal knowledge and its relationship to individual skill, were already at play in the community with which Harrison was obliged to engage in the mid-eighteenth century. The section of that community considered here, namely the astronomers, may seem the least concerned with this issue. It might be thought that astronomy had already achieved the kind of universality in the standing of its theories that had erased dependence on individual, embodied skill, and indeed that it was this characteristic that recommended an astronomical solution to the longitude problem. Horology and astronomy can seem to represent opposed, irreconcilable interests in the Harrison story, but similar concerns can be found around the question of embodied skill, even if Harrison did not appreciate this himself.
It might be helpful to explain that this is a study of eighteenth-century attitudes and ideas, some of which were at the time, as we shall see, applied specifically to Harrison.[2] Aspects of recent research would identify his achievement as principally ‘technological’, a term whose meaning has shifted over time and must be used with care so as not to import modern assumptions. The present article has little to say to an ambition to identify the ‘true’ character of Harrison’s accomplishment, though it may offer that project some help in explaining how Harrison was received and understood (or, it might be argued, ‘misunderstood’) in his time. Prominent among the notions that should be taken in the sense of the period are those surrounding the idea of ‘genius’.
Figure 1 : John Harrison © Science Museum/Science & Society Picture Library
https://dx.doi.org/10.15180/140209/007
The revisionist historiography of Harrison does not consider him a ‘lone genius’, as the title of Dava Sobel’s bestseller presents him (Sobel, 1996), but he had a ‘genius’ in the eighteenth-century sense of the word, which the Oxford English Dictionary defines as ‘Natural ability or capacity; quality of mind; attributes which suit a person for his or her peculiar work’ (OED, 2014). We shall try to remain within that sense of the word, while bringing two other men of genius into the story: John Dollond and, more especially, James Short. Of the two, Dollond has the greater prominence, in both the popular and the scholarly context, while Short is already associated with Harrison’s story. Both were telescope makers, but they represent quite different types of instrument, Dollond being famously linked to profound and far-reaching developments in the refractor (a telescope whose only optical components are lenses) and Short concerned exclusively with the reflector (where the main optical components are mirrors, though there will be lenses as well, at least in the eyepiece). For this reason we might have expected them to have been commercial rivals, but instead they seem to have been friends, collaborating, for example, over the application of the divided-object-glass micrometer to the Gregorian reflector.
Figure 2 : Thirty six inch reflecting telescope by James Short in 1769 © Science Museum/Science & Society Picture Library
https://dx.doi.org/10.15180/140209/008
The reflecting telescope and James Short
https://dx.doi.org/10.15180/140209/003
James Short described himself as an ‘optician solely for reflecting telescopes’ (Bryden, 1969; Clarke, 2006; Turner, 1969). A public avowal of that degree of specialism in the instrument trade was very unusual in eighteenth-century London. Makers who offered their wares in shops supplying retail customers were more inclined to maximise their apparent range, even though there surely were very specialised workmen either in the workshop behind the shop or, more likely, in the workshop of a subcontractor supplying parts or processes. Yet it was usual to give customers the impression of a business boasting a wide range of instruments. So how did Short come to be, in public, an optician solely for reflecting telescopes?
To understand this we have to go back to Newton’s account of his design for a reflector in the first edition of his Opticks of 1704, where he emphasises that he made his own telescopes – grinding and polishing the metal mirrors by hand. While he goes through the process in detail, he also makes the point that communication in words is of limited use: ‘This Art of polishing will be better learnt by repeated Practice than by my description’ (Newton, 1704, p 77).
Newton offers two contexts for proposing a shift from the refractor to the reflector. The one generally emphasised by historians is his tenet that colours are not created by the process of refraction: they pre-exist in the incident light and their different refractive properties mean that refraction inevitably results in their dispersion. Thus, dispersion into colours is unavoidable when light passes through a lens. Furthermore dispersion for a given degree of refraction is the same for all types of glass, so there can be no possibility of recombining the colours to give a resultant deviation without dispersion, and so a refracting telescope can never be perfected so as to give a truly sharp image.
Seeing therefore the Improvement of Telescopes of given lengths by Refractions is desperate; I contrived heretofore a Perspective by reflexion, using instead of an Object Glass a concave of Metal. (Newton, 1704, p 75)
Newton also presents his telescope construction under the title ‘To shorten telescopes’, that being an obvious desideratum of contemporary telescopic astronomy with its very long refractors. The combination of lenses and mirrors to shorten telescopes was also a concern of Robert Hooke, who had a telescope 60 feet in length, and both his and Newton’s designs were regarded as ‘catadioptrical’ instruments, rather than, at this stage, ‘reflecting’ telescopes, because they used combinations of mirrors and lenses (Bennett, 2006). The upshot of this work was that Newton’s legacy to the development of telescopic optics in Britain was a perhaps unexpected combination of geometrical and artisanal practice: practitioners analysed the geometry and the natural philosophy of the properties of light, but they also worked at making metal mirrors.
Given the character and content of Newton’s Opticks, the composition of the great Newtonian optical treatise of the eighteenth century by the Cambridge mathematician Robert Smith – his Opticks of 1738 – is, for the most part, unsurprising (Smith, 1738). It is organised into four ‘books’, denominated ‘popular’, ‘mathematical’, ‘mechanical’ and ‘philosophical’. ‘Mechanical’, referring to the design, manufacture and use of instruments, might be expected, but this is a very early use of ‘popular’ to describe an introductory scientific text for a general, non-specialised public. Newton’s Opticks was certainly mathematical, mechanical and philosophical, but it was hardly popular, despite being the most accessible of his books. Yet a popular culture of optics had begun to develop in the early decades of the century and Smith’s book would give it further impetus. A great many serious amateurs in astronomy and telescope-making began with Smith or encountered him at an early stage, while, increasingly, less committed participants had other resources to turn to in popular books, lecture series and instruments aimed at non-astronomers.
It was the instrument makers, rather than the mathematicians such as Smith, who further promoted this cultural and commercial opportunity. It was they who provided even more popular books and who sold the appropriate telescopes, for the most part Gregorian reflectors. The larger apertures possible with reflectors fitted them for viewing the Moon or Saturn in greater detail, or for marvelling at the variety of nebulae or clusters of stars, while the Gregorian had the intuitive advantage over the Newtonian that the observer was looking towards the object of interest. Rather than using the word ‘popular’, these authors were inclined to signal a general interest by offering their work to ladies as well as gentlemen: examples include James Ferguson’s An easy introduction to astronomy, for young gentlemen and ladies and Benjamin Martin’s The Young Gentleman and Lady’s Philosophy.
While certain instrument makers indulged in quasi-academic activity, such as writing textbooks, devising courses and giving lectures, more learned astronomers rolled up their sleeves and applied themselves to grinding and polishing. Smith describes these mechanical procedures in detail, presenting this as a polite occupation, appropriate to the rational gentleman. He can cite the activity of John Hadley, Vice-President of the Royal Society, James Bradley, Savilian Professor at Oxford, and Samuel Molyneux, a member of parliament and a privy counsellor from a family of Irish gentry. If it seems unexpected to find such men working by hand in casting, grinding and polishing, we might add that their methods were being published by the Plumian Professor in Cambridge, who would shortly become Master of Trinity College and Vice-Chancellor of the University. The legitimation for all this manual work was Newtonian.
Where are we to place James Short in this context? Born in Edinburgh in 1710 into an artisanal family, he was orphaned at an early age and was accepted into George Heriot’s Hospital as a pupil at the age of ten, moving to the Royal High School at 12 and eventually matriculating at the University of Edinburgh at 16 (Clarke, 2006). An early biography says he had already shown talents in handcraft – that is, in making things – and in the classics, and in the University he took to mathematics, giving up all former thoughts of the ministry. He attracted the attention, support and patronage of Colin MacLaurin, Professor of Mathematics, who was a follower and friend of Newton; indeed, MacLaurin had been appointed to succeed the Newtonian David Gregory to the Edinburgh chair with the help of Newton’s patronage.
Oil painting portrait of James Short
Figure 3 : A portrait of James Short © Royal Observatory Edinburgh
https://dx.doi.org/10.15180/140209/009
The question of the practicality of Newtonian reflecting telescopes had been under trial at the Royal Society, with Newton in the chair as President, in the early 1720s and now MacLaurin accommodated Short’s efforts to further this work in his own rooms at the University. Short worked mostly on Gregorians and, when MacLaurin wrote to Smith in 1734 of his success, Smith published the account in his Opticks. Short could hardly have had a more propitious introduction to the world of practical optics. He became a Fellow of the Royal Society on a visit to England in 1737 and he had a substantial reputation and a successful business by the time he moved his operations permanently to London in 1738, though he would always maintain his links with Edinburgh, where he visited regularly.
MacLaurin was a friend of James Douglas, Lord Aberdour, later Earl of Morton, an Edinburgh natural philosopher, who had himself become FRS just four years before Short. Douglas also became an early patron of Short’s, appointing him tutor to his children, and owning some of his telescopes. Short went with Morton to Orkney in 1739 on a surveying project, not only surveying Morton’s lands, but also working on determining the length of a degree of latitude.
Short managed to prosper in both business and scientific prestige. He became an active Fellow of the Royal Society, was called on for reports on various technical matters, published papers in the Philosophical Transactions, and operated a private observatory in his premises in Surrey Street. He served on the Council of the Society and his being in trade, as other important makers would find, did not prevent him from reaching a respected position in the London scientific world. The Newtonian basis of his craft was helpful in cultivating his position and I have suggested elsewhere that the trade description he adopted of ‘optician solely for reflecting telescopes’ could have been more than a mere statement of fact, but an assertion of his standing in the world of mathematical natural philosophy (Bennett, 2006, p 259). He died a wealthy man in 1768, leaving a fortune of about £20,000.
The marine timekeeper and John Harrison
https://dx.doi.org/10.15180/140209/004
The figure of £20,000 (the value of the full longitude reward) is not the only biographical coincidence between Short and John Harrison. Harrison too came to London in the 1730s and, supported by some of the same people who helped Short, began to interact with the metropolitan mathematicians and natural philosophers (Andrewes, 1996; King, 2008; Quill, 1966). Although both men offered their mechanical skill as their principal asset, they cut very different figures – Short a university-educated tutor to the aristocracy as well as a craftsman, Harrison a poorly educated and relatively inarticulate carpenter. We should remember also that Short’s mechanical skills were in an area where fellow practitioners included university professors, fellows of the Royal Society and gentlemen of means and status; his mechanical work took him into contemporary scientific practice, rather than separating him from it. Nonetheless, although the Harrison story is popularly associated with enmity, rivalry and bitterness towards the astronomers of the period, that does not characterise the early decades of his time in London.
The certificate provided to Harrison in 1735 proposing a trial for his marine timekeeper H1, which occasioned the first meeting of the Board of Longitude, was signed by four astronomers (as well at the instrument maker and occasional astronomer, George Graham FRS), at least two of whom – Robert Smith and James Bradley – were among the gentlemen mirror-polishers. When another certificate was provided to Harrison by fellows of the Royal Society in 1741 a further gentleman polisher, John Hadley, added his name. Harrison was encouraged by leading natural philosophers, accommodated sympathetically and supported financially by the Board of Longitude, and presented with the Royal Society’s highest award, the Copley Medal, in 1749.
If Short had the patronage of MacLaurin and was absolutely the right sort of mechanic to fit into the then-current Newtonian optics, how was Harrison’s case promoted in the context of eighteenth-century London? We find a clue in the address given by the Royal Society’s President, Martin Folkes, when presenting the Copley Medal:
Mr Harrison, who, before he came to this Town lived in a place called Barrow in the County of Lincoln, not far from Barton upon Humber, was not originally brought up to the business he now professes, tho’ he was afterwards directed to it, by curiosity and inclination, and by the strong impulses of a natural and uncommon genius, but such a one, as has been sometimes found, in other instances also, to carry those who have been possessed of it, much further than they could have been led by the most elaborate precepts and rules of art. Royal Society Journal Book, Copy, xx, p 184
We have noted the growing fashionable interest in natural philosophy in contemporary London, fed by instrument makers who sold instruments, wrote popular books and gave or accommodated courses of lectures, accompanied by engaging demonstrations. Their shops were for more than ‘getting and selling’: they were also spaces for instruction and demonstration, as they promoted the new culture of public natural philosophy (Bennett, 2002). Harrison entered this world as he became a minor celebrity in a London society discovering the polite enjoyment of natural philosophy and mathematical and mechanical ingenuity.
As early as 1736, when Harrison and his first timekeeper were committed to the care of the Captain of the Royal Navy ship Centurion for a trial voyage to Lisbon, the First Lord of the Admiralty told the Captain that, ‘The Instrument which is put on Board your Ship, has been approved by all the Mathematicians in Town that have seen it, (and few have not)’ – the text of the letter and the Captain’s reply are given in Horrins, 1835, pp 137–8. Citizens and strangers with an interest in the ingenious or the curious viewed the timekeeper either at the workshop of George Graham or later at Harrison’s home in Red Lion Square. Short also recorded that Harrison’s first timekeeper ‘was seen by every curious and ingenious person, who were pleased to go to his house’ (Short, 1752, p 521); it impressed John Bevis, when he saw it at Graham’s in 1735 (Journal of the House of Commons, 29, pp 546-53). As the number of timekeepers grew, Harrison placed them in a public viewing room, where the large machines were kept running. Benjamin Franklin, for example, paid to see them in 1757 (Andrewes, 1996A, pp 207–8).
To appreciate the impact of encountering what we know were perceived as mechanical marvels from the accounts of those who visited, we must imagine them set alongside what we know of the public demeanour of John Harrison. His difficulty with communicating cogently and expressing himself coherently was probably the principal reason for his published tracts being substantially prepared by others. On the one occasion when this was not so, in 1775, the tract A description concerning such mechanism as will afford a nice, or True mensuration of time was notoriously opaque. We need not rely on our own judgement of its intelligibility to Harrison’s contemporaries: ‘Any one who reads but a single page of this pamphlet will be convinced that Mr. H. is utterly unqualified to explain, by writing, his own notions, or to give a tolerable idea of his own inventions’ (Monthly Review, 1775, p 320). The reviewer then reproduced passages from Harrison’s text and offered ‘translations’.
Harrison was a country carpenter from a remote and obscure village in Lincolnshire with little in the way of formal education. He had no experience of metropolitan culture prior to his first visit to London, which occurred in 1730, or perhaps a little earlier, with a manuscript account of his horological inventions. He returned in 1735 with his first marine timekeeper. The Captain of the Centurion found him ‘a very sober, a very industrious, and withal, a very modest man’, fearing that these qualities were hardly sufficient for the ‘attempted impossibilities’ of a sea-going clock (Horrins, 1835, p 138). Harrison must have seemed utterly foreign to the admirals, churchmen, natural philosophers and mathematicians who were interested in the longitude problem, and even more so to the general audience for polite, rational and improving entertainment that was growing in fashionable society. His unassuming manner, unfamiliar speech and incoherent commentary (though that may have been particularly problematic in his written accounts) must have made an incongruous accompaniment to the mechanical grace and eloquence of his machines – the ‘sweetness’ of the motion, as William Stukeley put it, recalling the impression made by seeing the first timekeeper at Graham’s workshop (Andrewes, 1996A, p 207; Penney, 1996, p 298). The Gentleman’s Magazine, in reporting the first meeting of the Board of Longitude, presented the enigma as follows: ‘This ingenious Person was originally brought up a Joiner, and ‘tis thought by Mathematicians, his Machine is nearer finding out the Longitude than any ever attempted of this kind’ (Gentleman’s Magazine, 7, 1737, p 448). To emphasise the force of that observation, we might remember that one writer of the period judged that in the common view finding the longitude was ‘placed in the same degree of probability with the secret of prolonging life, the perpetual motion, and the squaring of the circle’ (ASTROPHILUS, 1761, p 437).
How could there be such a combination of inexperience and ingenuity? The very starkness of the contrast made the answer obvious: this was what Martin Folkes meant by a ‘natural and uncommon genius’. Remember that Folkes had emphasised that Harrison ‘was not originally brought up to the business he now professes’ but his genius had taken him much further than would have been possible ‘by the most elaborate precepts and rules of art’. Mechanical skill was normally acquired through a lengthy apprenticeship but in Harrison’s case a lack of education had allowed him to become the consummate mechanic: his natural abilities had not been clouded and dulled by the drudgery of training. There are eighteenth-century references to him as ‘nature’s mechanic’ (Hatton, 1773, p 22), while his obituarist in the Annual Register, reminding his readers that Harrison had been trained as a carpenter, referred to ‘the vigor of his natural abilities, if not even strengthened by the want of education’ (Annual Register, 1777). ‘Nature’s mechanic’ was a linguistic trope, because it combined the incongruous and traditionally opposed categories of the natural and artificial. It was a deliberate oxymoron that played to a notion that was gaining currency at exactly this time, that of natural, innate ability, or genius.
There is every indication that this was a notion with which James Short would have been sympathetic. He was surely Harrison’s most consistent supporter outside his immediate family. He defended Harrison’s priority over the gridiron pendulum in a paper published in the Philosophical Transactions. He was one of the friends – probably the principal one – who helped with composing the pamphlets presenting Harrison’s case to public or parliament, the person most commonly associated with this role and acknowledged as such at the time. When Harrison objected to requirements from the ‘Commissioners for the Discovery of Mr Harrison’s Watch’ in 1763, saying that he could not afford to employ workmen to make duplicates of his watch, Lord Morton told him ‘…if you cannot do it of yourself, you must get your friend Mr. Short or some other Friends to assist you’ (Bennett, 2002A, p 83). Short defended Harrison’s position during the proceedings of this Commission. Later Harrison nominated Short, together with Short’s colleague John Bevis, to examine the instruments to be used on the trial voyage to Barbados, and nominated him again for the subsequent calculations. Short appeared for Harrison’s case before a committee of the House of Commons in 1763 (Journal of the House of Commons, 29, pp 546–53).
Perhaps the most cited example of Short’s links to Harrison comes from the filling of the vacancy for Astronomer Royal following the death of Nathaniel Bliss in 1764. Nevil Maskelyne was appointed but the candidates had included John Michell and James Short. (Michell was yet another of those mathematicians engaged in polishing specula and making reflectors.) We have seen that Short and Lord Morton, now President of the Royal Society, had served together on the Commission appointed in 1763 for examining or, as it was expressed at the time, ‘discovering’ Harrison’s watch and that Short alone had sided with Harrison. This was to cost him now, in that Morton opposed the candidature of his former client and colleague.
That Short was disposed to support nature’s mechanic might well be imagined from his background and from other things we know about his friends and interests. The Edinburgh of his student days saw the first flowering of the set of ideas and principles associated with the Scottish Enlightenment, with Short’s first patron, Colin MacLaurin, an early participant. Short was a founder member of the Philosophical Society of Edinburgh, of which MacLaurin was the prime mover. The Society’s historian Roger Emerson presents it as an institution that ‘can be fitted into the wider context of the European Enlightenment’ (Emerson, 1979, p 154). In London, Short was a friend of his near contemporary David Hume, and a friend also of Benjamin Franklin. One of his supporters as a candidate for fellowship at the Royal Society was the mathematician John Eames, a man of known liberal views, in charge of a non-conformist academy. Although the author of Harrison’s tract An account of the proceedings is identified as a fellow of the Royal Society, and so was probably Short, when the French astronomer Jérôme Lalande, on a visit to London, was given a copy by Short himself in 1763 he was told that the work had been shared with the lawyer Taylor White. White was not a fellow, but was Treasurer of the Foundling Hospital, with its progressive philosophy of philanthropy and education. Martin Folkes, one of Harrison’s strongest supporters in the Royal Society, was a founding Vice-President of the Foundling Hospital from 1739 to 1747. It is not difficult to build a picture of Short’s attitudes and those of his circle that is conducive to notions of natural ability fostered by application and improvement.
The most detailed reference we have to the Greenwich appointment comes in a letter from Alexander Small to Franklin in 1764:
Mr. Short is a Candidate for Greenwich but having opposed Lord Morton in the £5000 afair [the Commissioners for the Discovery of Mr Harrison’s Watch], Lord Morton now opposes him and gives it as a reason that Mr Short is a Scotch Man, though he acknowledges that he is the fittest for it of any Man. Franklin Papers
This reference is well known to historians of the episode but there might be more to the charge of being a ‘Scotch Man’ than has been noted before, that is, more than a mere reference to Short’s origins. Morton had had a long time to come to terms with the fact that Short had been born in Scotland and it does not seem to have concerned him previously.
The Commission on which Morton and Short sat together in 1763, where Morton seems to have realised that Short was a ‘Scotch Man’, was concerned with what was called the ‘discovery’ of Harrison’s watch. The main Board had held that it was all very well for a watch, brought to a perfection of adjustment by the obsessive attentions of a dedicated maker, to keep time on a single voyage to the West Indies, but how did that solve the longitude problem if we did not know how the watch had been made? How could such watches be made by the generality of competent watchmakers, unless it was known on what principles it was based and by what methods constructed? The problem was more acute, of course, if the obsessive maker had ‘a natural and uncommon genius’, to quote Folkes again, so at this stage being ‘nature’s mechanic’ might be a liability instead of an asset.
It is interesting to note that the very same notion of natural genius was applied to Short as well as to Harrison. David Steuart Erskine, Earl of Buchan, published a brief biography of Short in 1792. He was well placed to write this, having a number of links to Short, including family connections to MacLaurin. He is the source of the stories of Short’s early mechanical abilities, which prompted him to observe:
It is much to be wished, that the early and natural symptoms of genius in children were more attended to. It is very true, indeed, that they generally imitate what they see about them, and that no conclusions can be drawn from the scratchings of a child in a painter’s house, or the cutting of sticks in a carpenter’s; but a genius manifested without any concomitant circumstances, strongly evinces the bent of the mind, and should be carefully attended to and fostered by those to whom the care of youth is intrusted. (Erskine, 1792, pp 252–3)
Buchan was a political reformer (a very unsuccessful one) and a friend of Benjamin Franklin; he supported the American colonists during the War of Independence and was involved with radical Corresponding Societies in the 1790s. It is interesting to see the continuing survival of this attitude to early ‘genius’ and its application in particular to the case of James Short.
Buchan also supplies evidence of Short’s support for Harrison’s cause continuing throughout his life. Short died in June 1768 and, purely to show the suddenness of his demise, Buchan tells us that ‘A few days before his death, he had dined with young Harrison, son of the inventor of the time piece, at his house in Shore Ditch, and had walked from that place in the evening to his own house at Newington Butts’. This was a distance of two or three miles.
The refracting telescope and John Dollond
https://dx.doi.org/10.15180/140209/005
A brief look at the case of John Dollond illustrates a different way of dealing with the problem of relating individual skill to universal principle. Here we find a reversal in the distribution of intellectual and mechanical aspirations among telescope makers, with mechanics passionately seeking the status of theorists and engaging in squabbles over their theoretical credentials. When Dollond presents himself in his portrait, there is not a telescope in sight, even though making and selling telescopes became his trade. Here he clearly reads Newton’s Opticks, the book on the table, and practices experimental natural philosophy: the two instruments in the composition are experimental demonstrations of the principle of achromatisation, separated from its application in the telescope.
Oil painting portrait of John Dollond
Figure 4 : Portrait of John Dollond © Science Museum/Science & Society Picture Library
https://dx.doi.org/10.15180/140209/010
Dollond began as a silk-weaver in a Huguenot family in the unfashionable district of Spitalfields in London but with optics becoming a field of general interest, open to all comers – the first ‘popular’ science as presented by Smith – Dollond encouraged his son Peter to take up this more profitable trade and also followed his own investigations (Clifton, 2013; Gee, 2014; Sorrenson, 2013; Willach, 1996). Naturally he began with complete confidence in Newton’s conclusions but he came to doubt the reliability of the assumption that the dispersion of light for a given degree of refraction was the same for all types of glass. His subsequent experiments showed that this was not the case and that high-lead ‘flint’ glass had a significantly greater dispersive power than the more common optical ‘crown’ glass. This opened the possibility for an ‘achromatic’ combination of two lenses that could produce overall deviation without dispersion. Newton had been wrong.
Dollond explained his technique in a paper to the Royal Society in 1758 (the paper was communicated to the Society by James Short) and he was awarded the Copley Medal. In the same year he also took out a patent on his new lenses. He was elected a fellow of the Royal Society in May 1761, with Short’s support, but died suddenly in November and his share in the patent passed to his son Peter.
In subsequent squabbles between Peter and the many London opticians who challenged his patent, Peter’s consistent position was that, whatever precedents there may have been to his achromatic lenses, his father had independently reached his practical technique on the basis of his theoretical command of Newtonian optics. It was central to Peter’s cause that his father had not simply been a jobbing optician, but a natural philosopher. We can note, for example, the stance he adopted in response to a challenge from Jesse Ramsden to the originality of his father’s work:
In the beginning of the year 1757 Mr Dollond having tried the…8th Expt. of the 2d part of the first book of Newton’s Opticks and by that means having discovered the new principle which was that the dissipation of the different coloured rays was not in the same proportion to the mean refraction, in water as in glass … (Bennett, 1998)
Peter acknowledged that there had been an early conversation between his father and one of the earlier makers, George Bass, but held that Bass himself had not understood the significance of what he had been saying: ‘He did not know that such a difference in the quality of two kinds of glass could be applied to any advantage. Mr Bass was a practical optician; not a theorist.’
With reflectors we found mathematicians with mechanical aspirations; with refractors we find mechanics anxious to be mathematicians. Optical mirrors entered the eighteenth century with scarcely any trade history but with an account of their manufacture in Newton’s Opticks, soon to be elaborated in Smith’s Opticks. Lenses, on the other hand, had a long history of obscure workshop practice and trade protection.
Discovering Harrison’s watch
https://dx.doi.org/10.15180/140209/006
We can now consider the challenge facing the ‘Commissioners for the Discovery of Mr Harrison’s Watch’. How were they to effect this ‘discovery’, which meant literally the uncovering of the watch and the revealing of its secrets? How could anyone else come to ‘know’ what Harrison seemed to know, so as to make use of that knowledge? Merely looking inside would not be sufficient. Harrison would have to take the watch apart, demonstrate how it worked, be subject to detailed questioning by experts, instruct others in the successful manufacture of similar watches and, worst of all, as he saw it, collaborate with what were called ‘experimental exhibitions’ – a term he said left him completely baffled. There were many links here to the culture of public experiment in the eighteenth century and it is not irrelevant that mathematicians had involved themselves with making optical mirrors. They had experience of the difficulties of adequately capturing and codifying such acquired skill: we have noted that Newton himself had written, ‘This Art of polishing will be better learnt by repeated Practice than by my description’.
The troubled and complex story of ‘discovering’ Harrison’s watch has been told elsewhere, but here we might consider Short’s situation through his time on the Commission. We have noted biographical links between Harrison and Short but here they were linked also through questions about the character of mechanical knowledge, the methodology of its communication and the possibilities for recording or codifying it in a set of rules or principles. This was precisely the burden of the ‘Commissioners for the Discovery of Mr Harrison’s Watch’ and James Short, who was one of their number, was involved on his own behalf with exactly these issues, though not under such public scrutiny as Harrison. At times his position between the trade, where manufacturing techniques were commercial assets, and the mathematical polishers, whose credit instead came from effective publication and recognition, was an uncomfortable one. How could Short make such superior telescopes, command such high prices, do so well in business? As a note added to the second (posthumous) edition of the Lectures on Natural and Experimental Philosophy of George Adams Junior put it: ‘From a principle unknown to a liberal philosopher, Mr. Short would not disclose the particular progresses by which he figured his metals; and at the time of his death they were supposed to die with him’ (Adams, 1799, 2, p 534).
There was a belief that Short had some secret method, formula or principle, either in the composition of his metal or in his technique for polishing, but no such secret was ever discovered, though it was looked for after his death. Gerard Turner has concluded that there was none: ‘It is very doubtful whether Short had any secret, other than his skill, dexterity and patience’ (Turner, 1969). MacLaurin had given just as simple an account as early as 1734: ‘He executes every part himself, and takes vast pains to make the instruments as perfect as possible’ (Smith, 1738, 2, pp 80–81).
In 1777 the physician John Mudge sought to publish the methods that were understood to be Short’s in a substantial paper in the Philosophical Transactions and such was the importance attached to this that he too was awarded the Copley Medal. In fact there was little in Mudge’s paper that was new and he was even doubtful whether such codification of mechanical skill was possible at all, admitting that his account could be only a partial one:
… I will describe it in the best manner I can; though many little circumstances which will be unavoidably omitted (and which at the same time are frequently essential to the success of a mechanic process) can only be supplied by actual experience. (Bennett, 2012, p 106)
Mudge’s attempts were taken up by the clergyman John Edwards, as the gentlemen mechanics continued their mirror-making to the end of the century, mired in attempts to express their acquired skills in words. Edwards agrees that: ‘a little Experience in these Matters will better suffice than a Volume written upon the Subject’ (Bennett, 2012, p 109). Most famously, William Herschel spent most of a lifetime acquiring this experience (still beginning by reading Smith’s Opticks) and made extensive and sustained efforts to prepare a treatise on polishing but never managed to complete it for publication. As a result, he too became suspected of keeping his methods secret and, like Short and Harrison, was criticised for this, though his manuscript record shows that he struggled and failed to achieve a secure codification that could have communicated his skills.
What has all this to do with Harrison? The familiar story sets the ambition, methodology and intellectual culture of eighteenth-century astronomy in opposition to the ethos and values of mechanical horology. As this is being challenged and revised more generally, the present study shows that the conundrum that faced the Board of Longitude – how to reconcile a clear case of individual genius with the need for a universal practice – was not unknown to the community of astronomers. It might be expected for some of the most influential members of the Board to have looked for a solution to the longitude problem in some natural principle – a discovery or an application from the natural world – or in a codification that could capture and communicate a mechanical technique. Yet in the contemporary development of the telescope they were more directly involved with the difficulty, perhaps the impossibility, of achieving any such codification. There the mathematicians themselves struggled to communicate the manual skills they had gained through their work with mirrors, while mechanics such as Dollond made less than convincing claims to a theoretical grounding for their mechanical practice.
Just as a longitude solution might have to depend uncomfortably on the particularity of mechanical genius, knowledge of some of the most elusive bodies in the heavens – such as nebulae and close double stars – depended on the seemingly arbitrary, manual talent and tactile sensitivity gained from many hours spent not studying optics but grinding and polishing mirrors. Members of the Board of Longitude, such as Robert Smith and James Bradley, had direct experience of such problems, while James Short had to negotiate his own path through the conundrum. He supplied the tools for revealing the heavenly bodies but the methods he used were largely unknown and had a contemporary reputation, almost certainly exaggerated, for secret particularity. In addition, Short’s empathy with Harrison surely derived some of its warmth from an intellectual culture that valued unschooled, unregulated, unspoilt, individual ‘genius’.
Tags
EIGHTEENTH CENTURY HISTORY OF ASTRONOMY HISTORY OF SCIENCE INSTRUMENT MAKERS SCIENTIFIC INSTRUMENTS
Footnotes
1. The conference ‘Longitudes Examined’ was held at the National Maritime Museum, Greenwich, 25–26 July 2014.
BACK TO TEXT
2. I am grateful to an anonymous reviewer for suggesting that this historiographical point needs to be explained.
BACK TO TEXT
References
Adams, G, 1799, Lectures on Natural and Experimental Philosophy (London: W and S Jones)
BACK TO TEXT
Andrewes, W (ed), 1996, The Quest of Longitude (Cambridge, Mass: Collection of Historical Scientific Instruments, Harvard University)
BACK TO TEXT
Andrewes, W, 1996A, ‘Even Newton could be wrong: the story of Harrison’s first three sea clocks’ in Andrewes, 1996, pp 190–234
BACK TO TEXT
Annual Register, 1777, ‘An account of the life of the late Mr. Harrison’, The Annual Register, 20, pp 24–6
BACK TO TEXT
ASTROPHILUS, 1761, ‘Of the inventions for discovering the longitude’, the Gentleman’s Magazine: and Historical Chronicle, 31, pp 437–9
BACK TO TEXT
Bennett, J, 1998, ‘Peter Dollond answers Jesse Ramsden’, Sphaera, 8, pp 4–5; http://www.mhs.ox.ac.uk/sphaera/index.htm?issue8/articl5 (accessed 23 August 2014)
BACK TO TEXT
Bennett, J, 2002, ‘Shopping for instruments in Paris and London’, in Smith, P H and Findlen, P (eds), Merchants and Marvels: Commerce, Science, and Art in Early Modern Europe (New York and London: Routledge), pp 370–95
BACK TO TEXT
Bennett, J, 2002A, ‘The travels and trials of Mr Harrison’s timekeeper’, in Bourguet, N-M, Licoppe, C and Sibum, H O (eds), Instruments, Travel and Science: Itineraries of Precision from the Seventeenth to the Twentieth Century (London: Routledge), pp 75–95
BACK TO TEXT
Bennett, J, 2006, ‘Catadioptrics and commerce in eighteenth-century London’, History of Science, 44, pp 247–78
BACK TO TEXT
Bennett, J, 2012, ‘The art of polishing: practice and prose in eighteenth-century telescope making’, in Morrison-Low, A, et al. (eds), From Earth-Bound to Satellite: Telescopes, Skills and Networks (Leiden: Brill), pp 103–21
BACK TO TEXT
Bryden, D, 1969, ‘James Short, MA, FRS, optician solely for reflecting telescopes’, University of Edinburgh Journal, 24 , pp 251–61
BACK TO TEXT
Clarke, T, 2006, ‘Short, James (1710–1768)’, Oxford Dictionary of National Biography, Oxford University Press, 2004; online edn, October 2006
BACK TO TEXT
Clifton, G, 2013, ‘Dollond family (per. 1750–1871)’, Oxford Dictionary of National Biography, Oxford University Press, 2004; online edn, September 2013
BACK TO TEXT
Dunn, R, and Higgitt, R, 2014, Ships, Clocks, and Stars. The Quest for Longitude (London: Harper Collins)
BACK TO TEXT
Emerson, R, 1979, ‘The Philosophical Society of Edinburgh 1737–1747’, The British Journal for the History of Science, 12, pp 154–91
BACK TO TEXT
Erskine, D, 1792, ‘Life of Mr James Short, Optician’, Transactions of the Society of Antiquaries of Scotland, 1, pp 251–6
BACK TO TEXT
Franklin Papers, The Papers of Benjamin Franklin Sponsored by The American Philosophical Society and Yale University, Digital Edition by The Packard Humanities Institute, http://franklinpapers.org/franklin/framedVolumes.jsp?vol=11&page=479a (accessed 23 August 2014)
Gee, B, 2014, edited McConnell, A and Morrison-Low, A, Francis Watkins and the Dollond Telescope Patent Controversy (Farnham: Ashgate)
BACK TO TEXT
Hatton, T, 1773, An Introduction to the Mechanical Part of Clock and Watch Work (London: T Longman and G Robinson)
BACK TO TEXT
Horrins, J, 1835, [Harrison, J], Memoirs of a Trait in the Character of George III (London: W Edwards)
BACK TO TEXT
King, A, 2008, ‘Harrison, John (bap. 1693, d. 1776)’, Oxford Dictionary of National Biography, Oxford University Press, 2004; online edn, January 2008
BACK TO TEXT
Monthly Review, 1775, ‘Art. VIII. A Description concerning such mechanism ...’, The Monthly Review, or Literary Journal, 53, pp 320–29
BACK TO TEXT
Newton, I, 1704, Opticks: or, a Treatise of the Reflexions, Refractions, Inflections and Colours of Light (London:Sam. Smith and Benj. Walford )
BACK TO TEXT
OED, 2014, Oxford English Dictionary, Oxford University Press, online edition 2014
BACK TO TEXT
Penney, D, 1996, ‘Thomas Mudge and the longitude: a reason to excel’, in The Quest for Longitude, Andrewes (ed), 1996, pp 294–309
BACK TO TEXT
Quill, H, 1966, John Harrison: The Man Who Found Longitude (London: John Baker)
BACK TO TEXT
Short, J, 1752, ‘A Letter of Mr. James Short, F. R. S. to the Royal Society, concerning the Inventor of the Contrivance in the Pendulum of a Clock, to Prevent the Irregularities of Its Motion by Heat and Cold’, Philosophical Transactions , 47, pp 517–24
BACK TO TEXT
Smith, R, 1738, A Compleat System of Opticks in Four Books, Viz. A Popular, a Mathematical, a Mechanical, and a Philosophical Treatise (Cambridge: for the author)
BACK TO TEXT
Sobel, D, 1996, Longitude. The True Story of a Lone Genius who Solved the Greatest Scientific Problem of his Time (London: Fourth Estate)
BACK TO TEXT
Sorrenson, R, 2013, Perfect Mechanics: Instrument Makers at the Royal Society of London in the Eighteenth Century (Boston, Mass: Docent)
BACK TO TEXT
Turner, G, 1969, ‘James Short, FRS, and his contribution to the construction of reflecting telescopes’, Notes and Records of the Royal Society of London, 24, pp 91–108
BACK TO TEXT
Willach, R, 1996, ‘New light on the invention of the achromatic telescope objective’, Notes and Records of the Royal Society of London, 50, pp 195–210
BACK TO TEXT

"""

import streamlit as st
from gliner import GLiNER
import nltk
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from collections import defaultdict

nltk.download('punkt')

# Load the GLiNER model
model = GLiNER.from_pretrained("urchade/gliner_base")

# Function to chunk text by sentences (preserving names and avoiding token breakups)
def chunk_text_by_sentences(text, max_length=512):
    sentences = nltk.sent_tokenize(text)
    chunks = []
    current_chunk = ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) <= max_length:
            current_chunk += " " + sentence
        else:
            chunks.append(current_chunk.strip())
            current_chunk = sentence

    if current_chunk:
        chunks.append(current_chunk.strip())

    return chunks

# Function to process a batch of chunks
def process_batch(chunks, labels):
    try:
        batch_text = " ".join(chunks)
        return model.predict_entities(batch_text, labels)
    except Exception as e:
        print(f"Error processing batch: {e}")
        return []

# Function to post-process entities (remove duplicates or merge adjacent entities if needed)
def post_process_entities(entities):
    processed = []
    seen = set()

    for entity in entities:
        entity_text = entity['text']
        if entity_text not in seen:
            processed.append(entity)
            seen.add(entity_text)

    return processed

# Function to annotate the text with entity labels
def annotate_text_with_entities(text, entities):
    annotated_text = text
    sorted_entities = sorted(entities, key=lambda x: text.find(x["text"]), reverse=True)

    for entity in sorted_entities:
        annotated_text = annotated_text.replace(entity["text"], f'{entity["text"]} [{entity["label"]}]')

    return annotated_text

# Function to handle entity extraction from long text
def extract_entities(text, labels, batch_size=3, max_workers=4):
    # Split text into manageable chunks by sentences
    chunks = chunk_text_by_sentences(text)

    all_entities = []

    # Process chunks in parallel using ThreadPoolExecutor with batch size
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []

        for i in range(0, len(chunks), batch_size):
            batch = chunks[i:i+batch_size]
            futures.append(executor.submit(process_batch, batch, labels))

        for future in as_completed(futures):
            try:
                entities = future.result()
                all_entities.extend(entities)
            except Exception as e:
                print(f"Error in thread: {e}")

    # Post-process entities to remove duplicates or merge adjacent ones
    return post_process_entities(all_entities)

# Function to count the number of different entities for each class
def count_entities_by_class(entities):
    entity_counts = defaultdict(int)

    for entity in entities:
        entity_counts[entity['label']] += 1

    return entity_counts

# Function to list all unique entities grouped by their types
def list_unique_entities_by_type(entities):
    unique_entities_by_type = defaultdict(set)

    for entity in entities:
        unique_entities_by_type[entity['label']].add(entity["text"])  # Group by label

    return unique_entities_by_type

# Streamlit UI starts here
st.title("Entity Recognition App")

# Input for text
input_text = st.text_area("Enter the text to process", height=200)

# Input for entity labels
st.write("Enter up to 5 entity labels:")
labels = [st.text_input(f"Label {i+1}", value="") for i in range(5)]

# Button to submit text and labels
if st.button("Submit"):
    # Filter empty labels
    labels = [label for label in labels if label]

    if input_text and labels:
        # Show progress bar
        progress_bar = st.progress(0)
        st.write("Processing...")

        # Extract entities
        entities = extract_entities(input_text, labels)

        # Update progress
        progress_bar.progress(100)

        # Annotate text
        annotated_text = annotate_text_with_entities(input_text, entities)
        st.subheader("Annotated Text:")
        st.write(annotated_text)

        # Show entity counts
        entity_counts = count_entities_by_class(entities)
        st.subheader("Entity Counts by Class:")
        for label, count in entity_counts.items():
            st.write(f"{label}: {count}")

        # Show unique entities grouped by type
        unique_entities_by_type = list_unique_entities_by_type(entities)
        st.subheader("Unique Entities Grouped by Type:")
        for entity_type, entity_set in unique_entities_by_type.items():
            st.write(f"**{entity_type.capitalize()}s:**")
            st.write(", ".join(entity_set))
    else:
        st.error("Please provide both text and at least one entity label.")